services:
  backend:
    image: first-hackaton
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "src.app:app", "--host", "0.0.0.0"]
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs/backend:/opt/logs
