services:
  backend:
    image: first-hackaton
    build:
      context: .
      dockerfile: Dockerfile
    command: ["uvicorn", "src.app:app", "--host", "0.0.0.0", "--reload"]
    restart: unless-stopped
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./logs/backend:/opt/logs
    depends_on:
      - redis

  redis:
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - ./data/redis:/data

  worker:
    command: [ "celery", "-A", "src.worker", "worker", "-l", "INFO" ]
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile
    image: first-hackaton
    volumes:
      - ./logs/worker:/opt/logs
    depends_on:
      - redis

  flower:
    image: mher/flower
    command: [ "celery", "-b", "redis://redis:6379", "flower" ]
    restart: unless-stopped
    ports:
      - "5555:5555"
    depends_on:
      - redis
